"""
Centralized configuration for the SOC Hashing Framework.
All tunable parameters for Certstream ingestion, hashing,
benchmarking, and output are defined here.
"""

import os  # Required for file path construction and environment variable access

# ─── Data Ingestion Configuration ───────────────────────────────────
# WebSocket URL for the Certstream Certificate Transparency real-time feed
CERTSTREAM_URL = "wss://certstream.calidog.io/"
# REST API endpoint for downloading recent malware URL payloads from URLhaus
URLHAUS_URL = "https://urlhaus.abuse.ch/downloads/json_recent/"
# REST API endpoint for fetching recent threat intelligence pulses from AlienVault OTX
OTX_URL = "https://otx.alienvault.com/api/v1/pulses/activity"

# Check environment for OTX API Key, fallback to empty string if not set
# OTX requires an API key for authenticated access; empty string triggers simulated fallback
OTX_API_KEY = os.environ.get("OTX_API_KEY", "")

# Maximum number of seconds the framework will collect data from a live feed before stopping
DEFAULT_COLLECTION_DURATION_SEC = 60        # seconds to collect live data
# Default number of log entries to collect per experimental run (user-configurable at runtime)
DEFAULT_BATCH_SIZE = 500                     # number of log entries per batch
# Timeout in seconds for establishing the Certstream WebSocket connection
CERTSTREAM_TIMEOUT_SEC = 10                  # WebSocket connect timeout

# Human-readable display names for each data source, used in console output and reports
DATASET_NAMES = {
    "certstream": "Certstream (Certificate Transparency Logs)",  # Real-time CT log events
    "urlhaus": "URLhaus (Malware URL Payloads)",                 # Abuse.ch malware URLs
    "otx": "AlienVault OTX (Threat Analytics Pulses)",           # OTX threat indicator pulses
    "cisa_ais": "CISA AIS (Automated Indicator Sharing)",        # Simulated government STIX/TAXII
}

# ─── Hashing Algorithms ─────────────────────────────────────────────
# List of all cryptographic hash algorithms to benchmark (internal identifiers)
HASH_ALGORITHMS = ["md5", "sha256", "sha3_256", "blake2b", "blake3"]

# Maps internal algorithm identifiers to human-readable names for charts and reports
ALGORITHM_DISPLAY_NAMES = {
    "md5":      "MD5",       # Legacy algorithm included for comparative baseline
    "sha256":   "SHA-256",   # NIST standard, widely used in SIEM and forensics
    "sha3_256": "SHA3-256",  # Keccak-based, NIST SHA-3 family
    "blake2b":  "BLAKE2b",   # High-speed hash from the BLAKE family (64-bit optimised)
    "blake3":   "BLAKE3",    # Latest BLAKE variant with parallelism support
}

# ─── Benchmarking ────────────────────────────────────────────────────
# Number of measured benchmark iterations per algorithm (after warmup)
BENCHMARK_ITERATIONS = 5                     # repeat benchmark runs
# Number of warmup iterations discarded before recording measurements (eliminates cold-start effects)
WARMUP_ITERATIONS = 2                        # discard initial runs
# Default percentage of entries deliberately tampered during tamper detection testing
DEFAULT_TAMPER_RATE = 20                     # % of entries deliberately tampered

# ─── Output Paths ────────────────────────────────────────────────────
# Absolute path to the directory containing this config file (project root)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Directory where all output artefacts (charts, CSVs, reports) are saved
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
# Subdirectory for PNG chart images generated by the visualiser
CHART_DIR = os.path.join(OUTPUT_DIR, "charts")
# Subdirectory for CSV data exports from the benchmark runner
CSV_DIR = os.path.join(OUTPUT_DIR, "csv")
# File path for the auto-generated Word document report
WORD_REPORT_PATH = os.path.join(OUTPUT_DIR, "test_walkthrough.docx")

# Maps numeric menu choices to short dataset names for the interactive CLI prompt
DATASET_NAMES_SHORT = {
    "1": "Certstream",       # Option 1 in the live dataset selection menu
    "2": "URLhaus",          # Option 2 in the live dataset selection menu
    "3": "AlienVault OTX",   # Option 3 in the live dataset selection menu
    "4": "CISA AIS"          # Option 4 in the live dataset selection menu
}

# Ensure output directories exist at import time so downstream modules can write files immediately
for _d in (OUTPUT_DIR, CHART_DIR, CSV_DIR):
    os.makedirs(_d, exist_ok=True)  # exist_ok=True prevents errors if directory already exists

# ─── Logging ─────────────────────────────────────────────────────────
# Format string for log messages: severity, timestamp, module name, and message
LOG_FORMAT = "[%(levelname)s %(asctime)s] %(name)s — %(message)s"
# Default logging level; set to INFO to capture pipeline progress without debug noise
LOG_LEVEL = "INFO"
